name: Linux build

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: install dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libx11-dev libxxf86vm-dev libxt-dev pkg-config libgtk2.0-dev libgtk-3-dev libxtst-dev gcc-11 g++-11
      - name: compile
        run: |
          ./gradlew tree-showing:jar
      - name: compile
        run: |
          export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16;
          ./gradlew -PjavacppPlatform=macosx-arm64 test
          ./gradlew -PjavacppPlatform=macosx-arm64 example:jar
          ./gradlew -PjavacppPlatform=macosx-arm64 javadoc