name: CI build

on: [push]

env:
  DISPLAY: ":99"
  XVFB_PARAMS: "-screen 0 1920x1080x24 -nolisten unix"
  RUNNING_ON_CI: true

jobs:
  builds:
    name: '${{ matrix.os }} with Java ${{ matrix.jdk }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17, 21, 23]
        os: [ubuntu-latest, windows-latest] #, macos-13]
      fail-fast: false
      max-parallel: 6
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Compile
        run: |
          ./gradlew jar
          ./gradlew example:jar

      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux'
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARAMS}} &

      - name: Test
        run: |
          ./gradlew test
        shell: bash

      - name: Javadoc
        run: |
          ./gradlew javadoc