name: CI build

on: [push]

env:
  RUNNING_ON_CI: true

jobs:
  builds:
    name: '${{ matrix.os }} with Java ${{ matrix.jdk }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17, 21, 23]
        os: [ubuntu-latest, windows-latest] #, macos-13]
      fail-fast: false
      max-parallel: 6
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Compile
        run: |
          ./gradlew jar
          ./gradlew example:jar

      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16;

      - name: Test
        run: |
          ./gradlew test
        shell: bash

      - name: Javadoc
        run: |
          ./gradlew javadoc