name: CI Release

on:
  release:
    types: [published]    # Triggers when a release is published
  workflow_dispatch:      # Allows manual triggering of the workflow

env:
  SANDEC_ARTIFACTORY_USERNAME: ${{secrets.SANDEC_ARTIFACTORY_USERNAME}}
  SANDEC_ARTIFACTORY_PASSWORD: ${{secrets.SANDEC_ARTIFACTORY_PASSWORD}}
  SANDEC_SIGNING_KEY_ID: ${{secrets.SANDEC_SIGNING_KEY_ID}}
  SANDEC_SIGNING_SECRET_KEY: ${{secrets.SANDEC_SIGNING_SECRET_KEY}}
  SANDEC_SIGNING_PASSWORD: ${{secrets.SANDEC_SIGNING_PASSWORD}}
  SANDEC_SONATYPE_USERNAME: ${{secrets.SANDEC_SONATYPE_USERNAME}}
  SANDEC_SONATYPE_PASSWORD: ${{secrets.SANDEC_SONATYPE_PASSWORD}}
  MAVEN_CENTRAL_AUTH_TOKEN: ${{secrets.MAVEN_CENTRAL_AUTH_TOKEN}}
  MAVEN_CENTRAL_PUBLISHING_TYPE: 'USER_MANAGED'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'JPro-one'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Print Release Version
        run: |
          RELEASE_VERSION=$(grep '^JPRO_PLATFORM_VERSION' gradle.properties | cut -d'=' -f2)
          echo "Release Version: $RELEASE_VERSION"

      - name: Publish to Sandec Public Repository
        run: |
          ./gradlew clean publish

      - name: Publish to Maven Central Sonatype
        run: |
          ./gradlew publishToMavenCentralPortal